# Site
repository: sproogen/resume-theme
favicon: images/mrjacob.ico

# Content configuration version
version: 2

# Personal info
name: Yakup Çatalkaya
title: Electronics Engineer
email: yakup@mrjacob.net
#website: scholar.google.com/citations?user=aCtp9fIAAAAJ&hl=tr

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: yakupcatalkaya
github_username:  yakupcatalkaya
# stackoverflow_username: "00000001"
# dribbble_username: yakupcatalkaya
# facebook_username: yakupcatalkaya
# flickr_username: yakupcatalkaya
#instagram_username: jameswgrant
linkedin_username: yakupcatalkaya
# xing_username: yakupcatalkaya
# pinterest_username: yakupcatalkaya
# youtube_username: yakupcatalkaya
# googleplus_username: +yakupcatalkaya
orcid_username: 0000-0002-6698-7376

# Additional icon links
additional_links:
- title: Google Scholar
  icon: fas fa-globe
  url: https://scholar.google.com/citations?user=aCtp9fIAAAAJ&hl=tr
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profil_jacob.jpg
about_content: | # this will include new lines to allow paragraphs
  Currently, I’m a junior Electrical and Electronic Engineering student at Bilkent University in Ankara, Turkey, and an undergraduate researcher in UMRAM. Meanwhile, I am interested in applications of Electronics engineering in the field of Neuroscience. In addition to that, I would like to pursue an academic career in Neuroscience.

  I am most skilled in: <mark>Electronics</mark> and <mark>Computational Neuroscience</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NeuroMatch 2021 Computational Neuroscience Course Project
        #link: github.com/yakupcatalkaya/NMA21_project
        link_text: Project Website
        additional_links:
          #- title:  NMA21 CN Project
          #  icon: fab fa-github
            #url: github.com/yakupcatalkaya/NMA21_project
           - title:  NMA21 CN Project
             icon: fab fa-github
             url: github.com/yakupcatalkaya/NMA21_project
        quote: >
          NeuroMatch 2021 ECoG Project
        description: | # this will include new lines to allow paragraphs
          Analyzed Kai Miller’s Faces&Houses ECoG dataset. Proposed the correlation between error rate and noise rate on stimuli that cause perceptual load while recognizing face stimuli.
      - layout: left
        title: Remote Psychology Experiment
        #link: github.com/yakupcatalkaya/psyc_experiment
        link_text: Project Website
        additional_links:
          - title:  Psychology Experiment
            icon: fab fa-github
            url: github.com/yakupcatalkaya/NMA21_project
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          UMRAM Remote Psychology Experiment
        description: | # this will include new lines to allow paragraphs
          An experiment has been designed via Pygame and acquired data has been visualized.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: National Magnetic Resonance Researcher Center (UMRAM)
        link: umram.bilkent.edu.tr
        # link_text: boringcompany.com
        sub_title: Undergraduate Researcher
        caption: Aug 2020- Present  | Ankara, Turkey
        quote: >
          Supervisor: Ausaf Ahmed Farooqui, Ph.D.
        description: | # this will include new lines to allow paragraphs
          Gaining expertise in fMRI analyses, EEG, and interdisciplinary neuroscience experiments.
          
      - layout: left
        title: AKES Intelligent Industrial Systems
        link: akesltd.com
        # link_text: boringcompany.com
        sub_title: Intern
        caption: June 2020- Aug 2020  | Ankara, Turkey  
        quote: >
          Supervisor: Mehmet Tugay Kaptanoğlu
        description: | # this will include new lines to allow paragraphs
          Designed and developed mechanical ventilator, and oxygen concentrator. 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Bilkent University
        caption: Sep 2017 - Jun 2023 (Expected) | Ankara, Turkey
        sub_title: BSc in Electrical and Electronic Engineering
        quote: 
          CGPA : 2.60/4.0
        description: | # this will include new lines to allow paragraphs
          # 

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Summer Schools & Certificates & Conferences
      - Neuromatch Academy 2021 Computational Neuroscience Summer School
      - Interview Adventure Interview Adventure with Talent Hunters, Bilkent University Career and Alumni Office, Certificate of Participation, 2020
      - 18th National Neuroscience Congress, Certificate of Participation, 2020
      - 6th Bilkent Neuroscience Days, Certificate of Participation, 2018
      Hobbies & Interests
      - Ham Radio
      - fountain pen
      - reading modern mythology and fiction books
      - watching sci-fiction movies and series
      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
